print cvsmbf(chr$(0) + chr$(0) + chr$(&h20) + chr$(&h84))
print cvsmbf(chr$(0) + chr$(0) + chr$(&h00) + chr$(&h82))
print cvsmbf(chr$(0) + chr$(0) + chr$(0) + chr$(&h81))
print cvsmbf(chr$(0) + chr$(0) + chr$(0) + chr$(0))
print cvsmbf(chr$(0) + chr$(0) + chr$(0) + chr$(&h80))
print cvsmbf(chr$(0) + chr$(0) + chr$(0) + chr$(&h7f))
print cvsmbf(chr$(0) + chr$(0) + chr$(&h80) + chr$(&h80))
print cvsmbf(chr$(&hf3) + chr$(&h04) + chr$(&h35) + chr$(&h80))
print cvsmbf(chr$(&hf3) + chr$(&h04) + chr$(&h35) + chr$(&h81))
print cvsmbf(chr$(&h18) + chr$(&h72) + chr$(&h31) + chr$(&h80))
print cvsmbf(chr$(&h3b) + chr$(&haa) + chr$(&h38) + chr$(&h81))
print cvsmbf(chr$(&hdb) + chr$(&h0f) + chr$(&h49) + chr$(&h81))
print cvsmbf(chr$(&hdb) + chr$(&h0f) + chr$(&h49) + chr$(&h83))
print cvsmbf(chr$(&hdb) + chr$(&h0) + chr$(&h0) + chr$(&h2))
print cvsmbf(chr$(&hdb) + chr$(&h0) + chr$(&h0) + chr$(&h3))
print cvsmbf(chr$(&hff) + chr$(&hff) + chr$(&hff) + chr$(&hff))

print mksmbf$(10)
print mksmbf$(2)
print mksmbf$(1)
print mksmbf$(0)
print mksmbf$(0.5)
print mksmbf$(0.25)
print mksmbf$(-0.5)