' Polymorphic float functions return single unless their argument is a double.
print atn(1)
print atn(1#)
print cos(1)
print cos(1#)
print exp(1)
print exp(1#)
print log(2)
print log(2#)
print sin(1)
print sin(1#)
print sqr(2)
print sqr(2#)
print tan(2)
print tan(2#)