print mid$("hello", 1, 0)
print mid$("hello", 1, 1)
print mid$("hello", 1, 2)
print mid$("hello", 1, 3)
print mid$("hello", 1, 4)
print mid$("hello", 1, 5)
print mid$("hello", 1, 6)
print mid$("hello", 2, 0)
print mid$("hello", 2, 1)
print mid$("hello", 2, 2)
print mid$("hello", 2, 3)
print mid$("hello", 2, 4)
print mid$("hello", 2, 5)
print mid$("hello", 2, 6)
print mid$("hello", 3, 0)
print mid$("hello", 3, 1)
print mid$("hello", 3, 2)
print mid$("hello", 3, 3)
print mid$("hello", 3, 4)
print mid$("hello", 3, 5)
print mid$("hello", 3, 6)
print mid$("hello", 4, 0)
print mid$("hello", 4, 1)
print mid$("hello", 4, 2)
print mid$("hello", 4, 3)
print mid$("hello", 4, 4)
print mid$("hello", 4, 5)
print mid$("hello", 4, 6)
print mid$("hello", 5, 0)
print mid$("hello", 5, 1)
print mid$("hello", 5, 2)
print mid$("hello", 5, 3)
print mid$("hello", 5, 4)
print mid$("hello", 5, 5)
print mid$("hello", 5, 6)
print mid$("hello", 6, 0)
print mid$("hello", 1)
print mid$("hello", 2)
print mid$("hello", 3)
print mid$("hello", 4)
print mid$("hello", 5)
print mid$("hello", 6)