export interface ScreenMode {
  mode: number;
  width: number;
  height: number;
  columns: number;
  rows: number;
  colors: number;
  attributes: number;
  defaultFgColor: number;
  pages: number;
  graphics: boolean;
  font: string;
  transform?: string;
}

export const SCREEN_MODES = [
  {
    mode: 0,
    width: 720,
    height: 400,
    columns: 80,
    rows: 25,
    colors: 64,
    attributes: 16,
    defaultFgColor: 7,
    pages: 8,
    graphics: false,
    font: 'Web IBM VGA 9x16',
    transform: 'scaleY(1.35)',
  },
  {
    mode: 1,
    width: 320,
    height: 200,
    columns: 40,
    rows: 25,
    colors: 16,
    attributes: 4,
    defaultFgColor: 3,
    pages: 1,
    graphics: true,
    font: 'Web IBM VGA 9x8',
    transform: 'scale(2, 2.5)',
  },
  {
    mode: 2,
    width: 640,
    height: 200,
    columns: 80,
    rows: 25,
    colors: 16,
    attributes: 2,
    defaultFgColor: 1,
    pages: 1,
    graphics: true,
    font: 'Web IBM VGA 9x8',
    transform: 'scale(1, 2.5)',
  },
  {
    mode: 7,
    width: 320,
    height: 200,
    columns: 40,
    rows: 25,
    colors: 16,
    attributes: 16,
    defaultFgColor: 15,
    pages: 8,
    graphics: true,
    font: 'Web IBM VGA 9x8',
    transform: 'scale(2, 2.5)',
  },
  {
    mode: 8,
    width: 640,
    height: 200,
    columns: 80,
    rows: 25,
    colors: 16,
    attributes: 16,
    defaultFgColor: 15,
    pages: 4,
    graphics: true,
    font: 'Web IBM VGA 9x8',
    transform: 'scale(1, 2.5)',
  },
  {
    mode: 9,
    width: 640,
    height: 350,
    columns: 80,
    rows: 25,
    colors: 64,
    attributes: 16,
    defaultFgColor: 15,
    pages: 2,
    graphics: false,
    font: 'Web IBM VGA 8x14',
    transform: 'scaleY(1.35)',
  },
  {
    mode: 10,
    width: 640,
    height: 350,
    columns: 80,
    rows: 25,
    colors: 9,
    attributes: 4,
    defaultFgColor: 3,
    pages: 2,
    graphics: false,
    font: 'Web IBM VGA 8x14',
    transform: 'scaleY(1.35)',
  },
  {
    mode: 11,
    width: 640,
    height: 480,
    columns: 80,
    rows: 30,
    colors: 262144,
    attributes: 2,
    defaultFgColor: 15,
    pages: 1,
    graphics: false,
    font: 'Web IBM VGA 8x16',
  },
  {
    mode: 12,
    width: 640,
    height: 480,
    columns: 80,
    rows: 30,
    colors: 262144,
    attributes: 16,
    defaultFgColor: 15,
    pages: 1,
    graphics: false,
    font: 'Web IBM VGA 8x16',
  },
  {
    mode: 13,
    width: 320,
    height: 200,
    columns: 40,
    rows: 25,
    colors: 262144,
    attributes: 256,
    defaultFgColor: 15,
    pages: 1,
    graphics: false,
    font: 'Web IBM VGA 9x8',
    transform: 'scale(2, 2.5)',
  },
];